#include "pythontarget.h"
#include <limits.h>
#include "low_level_platform/api/low_level_platform.h"
#include "include/api/schedule.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/threaded/scheduler.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
// Code generated by the Lingua Franca compiler from:
// file://home/csm126/lf-test/DeterminismTest_Python.lf
#define LOG_LEVEL 2


int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
const char* _lf_default_argv[] = { "dummy", "-f", "true", "-o", "500", "msec" };
void lf_set_default_command_line_options() {
        default_argc = 6;
        default_argv = _lf_default_argv;
}
#include "_sourcea.h"
#include "_sourceb.h"
#include "_adder.h"
#include "_logger.h"
#include "_determinismtest_python_main.h"
typedef enum {
    determinismtest_python_main,
    num_environments
} _enclave_id;
// The global array of environments associated with each enclave
static environment_t environments[num_environments];
// 'Create' and initialize the environments in the program
void lf_create_environments() {
    environment_init(&environments[determinismtest_python_main],"determinismtest_python_main",determinismtest_python_main,_lf_number_of_workers,2,0,0,0,3,0,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) environments;
   return num_environments;
}
// Arrays representing the enclaves downstream of `determinismtest_python_main_downstream`
#define DETERMINISMTEST_PYTHON_MAIN_NUM_DOWNSTREAM 0
// No downstreams, but 0-length arrays not allowed by MSVC (C2466)
int determinismtest_python_main_downstream[1] = {-1};
// Arrays representing the enclaves upstream of `determinismtest_python_main_upstream`
#define DETERMINISMTEST_PYTHON_MAIN_NUM_UPSTREAM 0
// No upstreams, but 0-length arrays not allowed by MSVC (C2466)
int determinismtest_python_main_upstream[1] = {-1};
// No upstreams, but 0-length arrays not allowed by MSVC (C2466)
interval_t determinismtest_python_main_upstream_delay[1] = {FOREVER};
// Writes a pointer to the array of upstream enclaves into `result` and returns the length
int lf_get_upstream_of(int enclave_id, int ** result) {
    int num_upstream;
    int* upstream;
    switch(enclave_id) { 
        case determinismtest_python_main:
            num_upstream = DETERMINISMTEST_PYTHON_MAIN_NUM_UPSTREAM;
            upstream = &determinismtest_python_main_upstream[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = upstream;
    return num_upstream;
}
// Writes a pointer to the array of downstream enclaves into `result` and returns the length
int lf_get_downstream_of(int enclave_id, int ** result) {
    int num_downstream;
    int* downstream;
    switch(enclave_id) { 
        case determinismtest_python_main:
            num_downstream = DETERMINISMTEST_PYTHON_MAIN_NUM_DOWNSTREAM;
            downstream = &determinismtest_python_main_downstream[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = downstream;
    return num_downstream;
}
// Writes a pointer to the array of upstream delays into `result` and returns the length
int lf_get_upstream_delay_of(int enclave_id, interval_t ** result) {
    int num_upstream;
    interval_t* delay;
    switch(enclave_id) { 
        case determinismtest_python_main:
            num_upstream = DETERMINISMTEST_PYTHON_MAIN_NUM_UPSTREAM;
            delay = &determinismtest_python_main_upstream_delay[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = delay;
    return num_upstream;
}
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int watchdog_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(watchdog_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _determinismtest_python_main_main_self_t* determinismtest_python_main_self[1];
    SUPPRESS_UNUSED_WARNING(determinismtest_python_main_self);
    _sourcea_self_t* determinismtest_python_a_self[1];
    SUPPRESS_UNUSED_WARNING(determinismtest_python_a_self);
    _sourceb_self_t* determinismtest_python_b_self[1];
    SUPPRESS_UNUSED_WARNING(determinismtest_python_b_self);
    _adder_self_t* determinismtest_python_add_self[1];
    SUPPRESS_UNUSED_WARNING(determinismtest_python_add_self);
    _logger_self_t* determinismtest_python_log_self[1];
    SUPPRESS_UNUSED_WARNING(determinismtest_python_log_self);
    // ***** Start initializing DeterminismTest_Python of class DeterminismTest_Python
    determinismtest_python_main_self[0] = new__determinismtest_python_main();
    determinismtest_python_main_self[0]->base.environment = &environments[determinismtest_python_main];
    determinismtest_python_main_self[0]->_lf_name = "determinismtest_python_main_lf";
    if (set_python_field_to_c_pointer("__main__",
        determinismtest_python_main_self[0]->_lf_name,
        0,
        "lf_self",
        determinismtest_python_main_self[0])) {
      lf_print_error_and_exit("Could not set lf_self pointer DeterminismTest_Python");
    }
    
    #if !defined LF_SINGLE_THREADED
    determinismtest_python_main_self[0]->base.reactor_mutex = NULL;
    #endif
    {
        _determinismtest_python_main_main_self_t *self = determinismtest_python_main_self[0];
        // ***** Start initializing DeterminismTest_Python.a of class SourceA
        determinismtest_python_a_self[0] = new__sourcea();
        determinismtest_python_a_self[0]->base.environment = &environments[determinismtest_python_main];
        determinismtest_python_a_self[0]->_lf_name = "determinismtest_python_a_lf";
        determinismtest_python_a_self[0]->_lf_py_reaction_function_0 = 
        get_python_function("__main__", 
            determinismtest_python_a_self[0]->_lf_name,
            0,
            "reaction_function_0");
        if(determinismtest_python_a_self[0]->_lf_py_reaction_function_0 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_0");
        }
        if (set_python_field_to_c_pointer("__main__",
            determinismtest_python_a_self[0]->_lf_name,
            0,
            "lf_self",
            determinismtest_python_a_self[0])) {
          lf_print_error_and_exit("Could not set lf_self pointer a");
        }
        
        
        // width of -2 indicates that it is not a multiport.
        determinismtest_python_a_self[0]->_lf_out_width = -2;
        // Initiaizing timer DeterminismTest_Python.a.t.
        determinismtest_python_a_self[0]->_lf__t.offset = 0;
        determinismtest_python_a_self[0]->_lf__t.period = MSEC(100);
        // Associate timer with the environment of its parent
        environments[determinismtest_python_main].timer_triggers[timer_triggers_count[determinismtest_python_main]++] = &determinismtest_python_a_self[0]->_lf__t;
        determinismtest_python_a_self[0]->_lf__t.mode = NULL;
    
        determinismtest_python_a_self[0]->_lf__reaction_0.deadline = NEVER;
        #if !defined LF_SINGLE_THREADED
        determinismtest_python_a_self[0]->base.reactor_mutex = NULL;
        #endif
        //***** End initializing DeterminismTest_Python.a
    }
    {
        _determinismtest_python_main_main_self_t *self = determinismtest_python_main_self[0];
        // ***** Start initializing DeterminismTest_Python.b of class SourceB
        determinismtest_python_b_self[0] = new__sourceb();
        determinismtest_python_b_self[0]->base.environment = &environments[determinismtest_python_main];
        determinismtest_python_b_self[0]->_lf_name = "determinismtest_python_b_lf";
        determinismtest_python_b_self[0]->_lf_py_reaction_function_0 = 
        get_python_function("__main__", 
            determinismtest_python_b_self[0]->_lf_name,
            0,
            "reaction_function_0");
        if(determinismtest_python_b_self[0]->_lf_py_reaction_function_0 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_0");
        }
        if (set_python_field_to_c_pointer("__main__",
            determinismtest_python_b_self[0]->_lf_name,
            0,
            "lf_self",
            determinismtest_python_b_self[0])) {
          lf_print_error_and_exit("Could not set lf_self pointer b");
        }
        
        
        // width of -2 indicates that it is not a multiport.
        determinismtest_python_b_self[0]->_lf_out_width = -2;
        // Initiaizing timer DeterminismTest_Python.b.t.
        determinismtest_python_b_self[0]->_lf__t.offset = 0;
        determinismtest_python_b_self[0]->_lf__t.period = MSEC(100);
        // Associate timer with the environment of its parent
        environments[determinismtest_python_main].timer_triggers[timer_triggers_count[determinismtest_python_main]++] = &determinismtest_python_b_self[0]->_lf__t;
        determinismtest_python_b_self[0]->_lf__t.mode = NULL;
    
        determinismtest_python_b_self[0]->_lf__reaction_0.deadline = NEVER;
        #if !defined LF_SINGLE_THREADED
        determinismtest_python_b_self[0]->base.reactor_mutex = NULL;
        #endif
        //***** End initializing DeterminismTest_Python.b
    }
    {
        _determinismtest_python_main_main_self_t *self = determinismtest_python_main_self[0];
        // ***** Start initializing DeterminismTest_Python.add of class Adder
        determinismtest_python_add_self[0] = new__adder();
        determinismtest_python_add_self[0]->base.environment = &environments[determinismtest_python_main];
        determinismtest_python_add_self[0]->_lf_name = "determinismtest_python_add_lf";
        determinismtest_python_add_self[0]->_lf_py_reaction_function_0 = 
        get_python_function("__main__", 
            determinismtest_python_add_self[0]->_lf_name,
            0,
            "reaction_function_0");
        if(determinismtest_python_add_self[0]->_lf_py_reaction_function_0 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_0");
        }
        if (set_python_field_to_c_pointer("__main__",
            determinismtest_python_add_self[0]->_lf_name,
            0,
            "lf_self",
            determinismtest_python_add_self[0])) {
          lf_print_error_and_exit("Could not set lf_self pointer add");
        }
        
        
        // width of -2 indicates that it is not a multiport.
        determinismtest_python_add_self[0]->_lf_sum_width = -2;
        // width of -2 indicates that it is not a multiport.
        determinismtest_python_add_self[0]->_lf_a_width = -2;
        // width of -2 indicates that it is not a multiport.
        determinismtest_python_add_self[0]->_lf_b_width = -2;
    
        determinismtest_python_add_self[0]->_lf__reaction_0.deadline = NEVER;
        #if !defined LF_SINGLE_THREADED
        determinismtest_python_add_self[0]->base.reactor_mutex = NULL;
        #endif
        //***** End initializing DeterminismTest_Python.add
    }
    {
        _determinismtest_python_main_main_self_t *self = determinismtest_python_main_self[0];
        // ***** Start initializing DeterminismTest_Python.log of class Logger
        determinismtest_python_log_self[0] = new__logger();
        determinismtest_python_log_self[0]->base.environment = &environments[determinismtest_python_main];
        determinismtest_python_log_self[0]->_lf_name = "determinismtest_python_log_lf";
        determinismtest_python_log_self[0]->_lf_py_reaction_function_0 = 
        get_python_function("__main__", 
            determinismtest_python_log_self[0]->_lf_name,
            0,
            "reaction_function_0");
        if(determinismtest_python_log_self[0]->_lf_py_reaction_function_0 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_0");
        }
        if (set_python_field_to_c_pointer("__main__",
            determinismtest_python_log_self[0]->_lf_name,
            0,
            "lf_self",
            determinismtest_python_log_self[0])) {
          lf_print_error_and_exit("Could not set lf_self pointer log");
        }
        // width of -2 indicates that it is not a multiport.
        determinismtest_python_log_self[0]->_lf__in_width = -2;
    
        determinismtest_python_log_self[0]->_lf__reaction_0.deadline = NEVER;
        #if !defined LF_SINGLE_THREADED
        determinismtest_python_log_self[0]->base.reactor_mutex = NULL;
        #endif
        //***** End initializing DeterminismTest_Python.log
    }
    //***** End initializing DeterminismTest_Python
    // **** Start deferred initialize for DeterminismTest_Python
    {
        determinismtest_python_main_self[0]->base.name = "DeterminismTest_Python";
        determinismtest_python_main_self[0]->base.parent = (self_base_t*)NULL;
    
    
    
        // **** Start deferred initialize for DeterminismTest_Python.a
        {
            determinismtest_python_a_self[0]->base.name = "a";
            determinismtest_python_a_self[0]->base.parent = (self_base_t*)determinismtest_python_main_self[0];
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of DeterminismTest_Python.a.
            determinismtest_python_a_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            determinismtest_python_a_self[0]->_lf__reaction_0.triggers = (trigger_t***)lf_allocate(
                    1, sizeof(trigger_t**),
                    &determinismtest_python_a_self[0]->base.allocations);
            determinismtest_python_a_self[0]->_lf__reaction_0.triggered_sizes = (int*)lf_allocate(
                    1, sizeof(int),
                    &determinismtest_python_a_self[0]->base.allocations);
            determinismtest_python_a_self[0]->_lf__reaction_0.output_produced = (bool**)lf_allocate(
                    1, sizeof(bool*),
                    &determinismtest_python_a_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    determinismtest_python_a_self[0]->_lf__reaction_0.output_produced[count++] = &determinismtest_python_a_self[0]->_lf_out.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of DeterminismTest_Python.a
        
        }
        // **** End of deferred initialize for DeterminismTest_Python.a
        // **** Start deferred initialize for DeterminismTest_Python.b
        {
            determinismtest_python_b_self[0]->base.name = "b";
            determinismtest_python_b_self[0]->base.parent = (self_base_t*)determinismtest_python_main_self[0];
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of DeterminismTest_Python.b.
            determinismtest_python_b_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            determinismtest_python_b_self[0]->_lf__reaction_0.triggers = (trigger_t***)lf_allocate(
                    1, sizeof(trigger_t**),
                    &determinismtest_python_b_self[0]->base.allocations);
            determinismtest_python_b_self[0]->_lf__reaction_0.triggered_sizes = (int*)lf_allocate(
                    1, sizeof(int),
                    &determinismtest_python_b_self[0]->base.allocations);
            determinismtest_python_b_self[0]->_lf__reaction_0.output_produced = (bool**)lf_allocate(
                    1, sizeof(bool*),
                    &determinismtest_python_b_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    determinismtest_python_b_self[0]->_lf__reaction_0.output_produced[count++] = &determinismtest_python_b_self[0]->_lf_out.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of DeterminismTest_Python.b
        
        }
        // **** End of deferred initialize for DeterminismTest_Python.b
        // **** Start deferred initialize for DeterminismTest_Python.add
        {
            determinismtest_python_add_self[0]->base.name = "add";
            determinismtest_python_add_self[0]->base.parent = (self_base_t*)determinismtest_python_main_self[0];
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of DeterminismTest_Python.add.
            determinismtest_python_add_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            determinismtest_python_add_self[0]->_lf__reaction_0.triggers = (trigger_t***)lf_allocate(
                    1, sizeof(trigger_t**),
                    &determinismtest_python_add_self[0]->base.allocations);
            determinismtest_python_add_self[0]->_lf__reaction_0.triggered_sizes = (int*)lf_allocate(
                    1, sizeof(int),
                    &determinismtest_python_add_self[0]->base.allocations);
            determinismtest_python_add_self[0]->_lf__reaction_0.output_produced = (bool**)lf_allocate(
                    1, sizeof(bool*),
                    &determinismtest_python_add_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    determinismtest_python_add_self[0]->_lf__reaction_0.output_produced[count++] = &determinismtest_python_add_self[0]->_lf_sum.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of DeterminismTest_Python.add
        
        }
        // **** End of deferred initialize for DeterminismTest_Python.add
        // **** Start deferred initialize for DeterminismTest_Python.log
        {
            determinismtest_python_log_self[0]->base.name = "log";
            determinismtest_python_log_self[0]->base.parent = (self_base_t*)determinismtest_python_main_self[0];
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of DeterminismTest_Python.log.
            determinismtest_python_log_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of DeterminismTest_Python.log
        
        }
        // **** End of deferred initialize for DeterminismTest_Python.log
    }
    // **** End of deferred initialize for DeterminismTest_Python
    // **** Start non-nested deferred initialize for DeterminismTest_Python
    {
    
    
    
        // **** Start non-nested deferred initialize for DeterminismTest_Python.a
        {
        
            // For reference counting, set num_destinations for port DeterminismTest_Python.a.out.
            // Iterate over range DeterminismTest_Python.a.out(0,1)->[DeterminismTest_Python.add.a(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                determinismtest_python_a_self[src_runtime]->_lf_out._base.num_destinations = 1;
                determinismtest_python_a_self[src_runtime]->_lf_out._base.source_reactor = (self_base_t*)determinismtest_python_a_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range DeterminismTest_Python.a.out(0,1)->[DeterminismTest_Python.add.a(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 0 of DeterminismTest_Python.a triggers 1 downstream reactions
                    // through port DeterminismTest_Python.a.out.
                    determinismtest_python_a_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 0 of DeterminismTest_Python.a, allocate an
                    // array of trigger pointers for downstream reactions through port DeterminismTest_Python.a.out
                    trigger_t** trigger_array = (trigger_t**)lf_allocate(
                            1, sizeof(trigger_t*),
                            &determinismtest_python_a_self[src_runtime]->base.allocations); 
                    determinismtest_python_a_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges DeterminismTest_Python.a.out(0,1)->[DeterminismTest_Python.add.a(0,1)] and DeterminismTest_Python.add.a(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range DeterminismTest_Python.add.a(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port DeterminismTest_Python.add.a's trigger struct.
                        determinismtest_python_a_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &determinismtest_python_add_self[dst_runtime]->_lf__a;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for DeterminismTest_Python.a
        // **** Start non-nested deferred initialize for DeterminismTest_Python.b
        {
        
            // For reference counting, set num_destinations for port DeterminismTest_Python.b.out.
            // Iterate over range DeterminismTest_Python.b.out(0,1)->[DeterminismTest_Python.add.b(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                determinismtest_python_b_self[src_runtime]->_lf_out._base.num_destinations = 1;
                determinismtest_python_b_self[src_runtime]->_lf_out._base.source_reactor = (self_base_t*)determinismtest_python_b_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range DeterminismTest_Python.b.out(0,1)->[DeterminismTest_Python.add.b(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 0 of DeterminismTest_Python.b triggers 1 downstream reactions
                    // through port DeterminismTest_Python.b.out.
                    determinismtest_python_b_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 0 of DeterminismTest_Python.b, allocate an
                    // array of trigger pointers for downstream reactions through port DeterminismTest_Python.b.out
                    trigger_t** trigger_array = (trigger_t**)lf_allocate(
                            1, sizeof(trigger_t*),
                            &determinismtest_python_b_self[src_runtime]->base.allocations); 
                    determinismtest_python_b_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges DeterminismTest_Python.b.out(0,1)->[DeterminismTest_Python.add.b(0,1)] and DeterminismTest_Python.add.b(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range DeterminismTest_Python.add.b(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port DeterminismTest_Python.add.b's trigger struct.
                        determinismtest_python_b_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &determinismtest_python_add_self[dst_runtime]->_lf__b;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for DeterminismTest_Python.b
        // **** Start non-nested deferred initialize for DeterminismTest_Python.add
        {
        
            // For reference counting, set num_destinations for port DeterminismTest_Python.add.sum.
            // Iterate over range DeterminismTest_Python.add.sum(0,1)->[DeterminismTest_Python.log._in(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                determinismtest_python_add_self[src_runtime]->_lf_sum._base.num_destinations = 1;
                determinismtest_python_add_self[src_runtime]->_lf_sum._base.source_reactor = (self_base_t*)determinismtest_python_add_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range DeterminismTest_Python.add.sum(0,1)->[DeterminismTest_Python.log._in(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 0 of DeterminismTest_Python.add triggers 1 downstream reactions
                    // through port DeterminismTest_Python.add.sum.
                    determinismtest_python_add_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 0 of DeterminismTest_Python.add, allocate an
                    // array of trigger pointers for downstream reactions through port DeterminismTest_Python.add.sum
                    trigger_t** trigger_array = (trigger_t**)lf_allocate(
                            1, sizeof(trigger_t*),
                            &determinismtest_python_add_self[src_runtime]->base.allocations); 
                    determinismtest_python_add_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges DeterminismTest_Python.add.sum(0,1)->[DeterminismTest_Python.log._in(0,1)] and DeterminismTest_Python.log._in(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range DeterminismTest_Python.log._in(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port DeterminismTest_Python.log._in's trigger struct.
                        determinismtest_python_add_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &determinismtest_python_log_self[dst_runtime]->_lf___in;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for DeterminismTest_Python.add
        // **** Start non-nested deferred initialize for DeterminismTest_Python.log
        {
        
        
        
        
        }
        // **** End of non-nested deferred initialize for DeterminismTest_Python.log
    }
    // **** End of non-nested deferred initialize for DeterminismTest_Python
    // Connect inputs and outputs for reactor DeterminismTest_Python.
    // Connect inputs and outputs for reactor DeterminismTest_Python.a.
    // Connect DeterminismTest_Python.a.out(0,1)->[DeterminismTest_Python.add.a(0,1)] to port DeterminismTest_Python.add.a(0,1)
    // Iterate over ranges DeterminismTest_Python.a.out(0,1)->[DeterminismTest_Python.add.a(0,1)] and DeterminismTest_Python.add.a(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range DeterminismTest_Python.add.a(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            determinismtest_python_add_self[dst_runtime]->_lf_a = (_adder_a_t*)&determinismtest_python_a_self[src_runtime]->_lf_out;
        }
    }
    // Connect inputs and outputs for reactor DeterminismTest_Python.b.
    // Connect DeterminismTest_Python.b.out(0,1)->[DeterminismTest_Python.add.b(0,1)] to port DeterminismTest_Python.add.b(0,1)
    // Iterate over ranges DeterminismTest_Python.b.out(0,1)->[DeterminismTest_Python.add.b(0,1)] and DeterminismTest_Python.add.b(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range DeterminismTest_Python.add.b(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            determinismtest_python_add_self[dst_runtime]->_lf_b = (_adder_b_t*)&determinismtest_python_b_self[src_runtime]->_lf_out;
        }
    }
    // Connect inputs and outputs for reactor DeterminismTest_Python.add.
    // Connect DeterminismTest_Python.add.sum(0,1)->[DeterminismTest_Python.log._in(0,1)] to port DeterminismTest_Python.log._in(0,1)
    // Iterate over ranges DeterminismTest_Python.add.sum(0,1)->[DeterminismTest_Python.log._in(0,1)] and DeterminismTest_Python.log._in(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range DeterminismTest_Python.log._in(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            determinismtest_python_log_self[dst_runtime]->_lf__in = (_logger__in_t*)&determinismtest_python_add_self[src_runtime]->_lf_sum;
        }
    }
    // Connect inputs and outputs for reactor DeterminismTest_Python.log.
    {
    }
    {
    }
    {
    }
    {
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add output port DeterminismTest_Python.a.out to array of is_present fields.
            environments[determinismtest_python_main].is_present_fields[(0) * 1 + 0 + count] = &determinismtest_python_a_self[0]->_lf_out.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add output port DeterminismTest_Python.a.out to array of intended_tag fields.
            environments[determinismtest_python_main]._lf_intended_tag_fields[(0) * 1 + 0 + count] = &determinismtest_python_a_self[0]->_lf_out.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add output port DeterminismTest_Python.b.out to array of is_present fields.
            environments[determinismtest_python_main].is_present_fields[(0) * 1 + 1 + count] = &determinismtest_python_b_self[0]->_lf_out.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add output port DeterminismTest_Python.b.out to array of intended_tag fields.
            environments[determinismtest_python_main]._lf_intended_tag_fields[(0) * 1 + 1 + count] = &determinismtest_python_b_self[0]->_lf_out.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add output port DeterminismTest_Python.add.sum to array of is_present fields.
            environments[determinismtest_python_main].is_present_fields[(0) * 1 + 2 + count] = &determinismtest_python_add_self[0]->_lf_sum.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add output port DeterminismTest_Python.add.sum to array of intended_tag fields.
            environments[determinismtest_python_main]._lf_intended_tag_fields[(0) * 1 + 2 + count] = &determinismtest_python_add_self[0]->_lf_sum.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    
    // Set reaction priorities for ReactorInstance DeterminismTest_Python
    {
    
        // Set reaction priorities for ReactorInstance DeterminismTest_Python.a
        {
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            determinismtest_python_a_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
        }
    
    
        // Set reaction priorities for ReactorInstance DeterminismTest_Python.b
        {
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            determinismtest_python_b_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
        }
    
    
        // Set reaction priorities for ReactorInstance DeterminismTest_Python.add
        {
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            determinismtest_python_add_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 1);
        }
    
    
        // Set reaction priorities for ReactorInstance DeterminismTest_Python.log
        {
            // index is the OR of level 2 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            determinismtest_python_log_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 2);
        }
    
    }
    
    // Initialize the scheduler for enclave `determinismtest_python_main` in a private scope
    {
        size_t num_reactions_per_level[3] = {2, 1, 1};
        sched_params_t sched_params = (sched_params_t) {
            .num_reactions_per_level = &num_reactions_per_level[0],
            .num_reactions_per_level_size = (size_t) 3
        };
        lf_sched_init(
            &environments[determinismtest_python_main],
            environments[determinismtest_python_main].num_workers,
            &sched_params
        );
    }
    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&environments[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
 #ifdef FEDERATED_CENTRALIZED
     lf_latest_tag_confirmed(tag_to_send);
 #else
     (void) tag_to_send;
 #endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void lf_terminate_execution(environment_t* env) {
    (void) env;
}
#endif
