// Code generated by the Lingua Franca compiler from:
// file://home/csm126/lf-test/HelloWorld_C.lf
#define LOG_LEVEL 2

#include <limits.h>
#include "low_level_platform/api/low_level_platform.h"
#include "include/api/schedule.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/threaded/scheduler.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);

int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
const char* _lf_default_argv[] = { "dummy", "-o", "1", "msec" };
void lf_set_default_command_line_options() {
        default_argc = 4;
        default_argv = _lf_default_argv;
}
#include "_helloworld_c_main.h"
typedef enum {
    helloworld_c_main,
    num_environments
} _enclave_id;
// The global array of environments associated with each enclave
static environment_t environments[num_environments];
// 'Create' and initialize the environments in the program
void lf_create_environments() {
    environment_init(&environments[helloworld_c_main],"helloworld_c_main",helloworld_c_main,_lf_number_of_workers,1,0,0,0,0,0,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) environments;
   return num_environments;
}
// Arrays representing the enclaves downstream of `helloworld_c_main_downstream`
#define HELLOWORLD_C_MAIN_NUM_DOWNSTREAM 0
// No downstreams, but 0-length arrays not allowed by MSVC (C2466)
int helloworld_c_main_downstream[1] = {-1};
// Arrays representing the enclaves upstream of `helloworld_c_main_upstream`
#define HELLOWORLD_C_MAIN_NUM_UPSTREAM 0
// No upstreams, but 0-length arrays not allowed by MSVC (C2466)
int helloworld_c_main_upstream[1] = {-1};
// No upstreams, but 0-length arrays not allowed by MSVC (C2466)
interval_t helloworld_c_main_upstream_delay[1] = {FOREVER};
// Writes a pointer to the array of upstream enclaves into `result` and returns the length
int lf_get_upstream_of(int enclave_id, int ** result) {
    int num_upstream;
    int* upstream;
    switch(enclave_id) { 
        case helloworld_c_main:
            num_upstream = HELLOWORLD_C_MAIN_NUM_UPSTREAM;
            upstream = &helloworld_c_main_upstream[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = upstream;
    return num_upstream;
}
// Writes a pointer to the array of downstream enclaves into `result` and returns the length
int lf_get_downstream_of(int enclave_id, int ** result) {
    int num_downstream;
    int* downstream;
    switch(enclave_id) { 
        case helloworld_c_main:
            num_downstream = HELLOWORLD_C_MAIN_NUM_DOWNSTREAM;
            downstream = &helloworld_c_main_downstream[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = downstream;
    return num_downstream;
}
// Writes a pointer to the array of upstream delays into `result` and returns the length
int lf_get_upstream_delay_of(int enclave_id, interval_t ** result) {
    int num_upstream;
    interval_t* delay;
    switch(enclave_id) { 
        case helloworld_c_main:
            num_upstream = HELLOWORLD_C_MAIN_NUM_UPSTREAM;
            delay = &helloworld_c_main_upstream_delay[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = delay;
    return num_upstream;
}
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int watchdog_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(watchdog_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _helloworld_c_main_main_self_t* helloworld_c_main_self[1];
    SUPPRESS_UNUSED_WARNING(helloworld_c_main_self);
    // ***** Start initializing HelloWorld_C of class HelloWorld_C
    helloworld_c_main_self[0] = new__helloworld_c_main();
    helloworld_c_main_self[0]->base.environment = &environments[helloworld_c_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    // Initiaizing timer HelloWorld_C.t.
    helloworld_c_main_self[0]->_lf__t.offset = 0;
    helloworld_c_main_self[0]->_lf__t.period = 0;
    // Associate timer with the environment of its parent
    environments[helloworld_c_main].timer_triggers[timer_triggers_count[helloworld_c_main]++] = &helloworld_c_main_self[0]->_lf__t;
    helloworld_c_main_self[0]->_lf__t.mode = NULL;
    
    helloworld_c_main_self[0]->_lf__reaction_0.deadline = NEVER;
    #if !defined LF_SINGLE_THREADED
    helloworld_c_main_self[0]->base.reactor_mutex = NULL;
    #endif
    //***** End initializing HelloWorld_C
    // **** Start deferred initialize for HelloWorld_C
    {
        helloworld_c_main_self[0]->base.name = "HelloWorld_C";
        helloworld_c_main_self[0]->base.parent = (self_base_t*)NULL;
    
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of HelloWorld_C.
        helloworld_c_main_self[0]->_lf__reaction_0.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 0 of HelloWorld_C
    
    }
    // **** End of deferred initialize for HelloWorld_C
    // **** Start non-nested deferred initialize for HelloWorld_C
    {
    
    
    
    }
    // **** End of non-nested deferred initialize for HelloWorld_C
    // Connect inputs and outputs for reactor HelloWorld_C.

    
    // Set reaction priorities for ReactorInstance HelloWorld_C
    {
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        helloworld_c_main_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
    }
    
    // Initialize the scheduler for enclave `helloworld_c_main` in a private scope
    {
        size_t num_reactions_per_level[1] = {1};
        sched_params_t sched_params = (sched_params_t) {
            .num_reactions_per_level = &num_reactions_per_level[0],
            .num_reactions_per_level_size = (size_t) 1
        };
        lf_sched_init(
            &environments[helloworld_c_main],
            environments[helloworld_c_main].num_workers,
            &sched_params
        );
    }
    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&environments[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
 #ifdef FEDERATED_CENTRALIZED
     lf_latest_tag_confirmed(tag_to_send);
 #else
     (void) tag_to_send;
 #endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void lf_terminate_execution(environment_t* env) {
    (void) env;
}
#endif
